### ISSUE TITLE
After click start game isn't start

### ISSUE THREAD

**Issue by omegatari** [Leayal/ReShade-Installer-For-PSO2#1]
After installation Reshade 3.0 with SweetFX2.0.8 with recommended setting
PSO2 Tweaker completely worked fine
but pso2.exe start at little sec then it's gone.
and Pso2 tweaker still exist

what happened?
pso2h.log didn't say anything because pso2 not run correctly its just appeared at task manager and then disappeared.

**Comment by Leayal** [comment]
Can you provide more info about the `recommended setting` ???

**Comment by Leayal** [comment]
Auto-close because of no response over 20 days.
Feel free to re-open if you need to.
